steps:
- name: 'docker/compose:1.24.1'
  args: ["-f", "docker-compose-1.yml", "up", "-d"]

- name: 'anshulpatel25/gcp:latest'
  entrypoint: 'bash'
  args:
    - '-cex'
    - |
      docker-compose up -d
      curl http://nginx
      curl http://localhost:8080 || echo "Won't work"
      curl http://127.0.0.1:8080 || echo "Won't work"
