steps:
- name: 'anshulpatel25/gcp:latest'
  entrypoint: 'bash'
  args:
    - '-cex'
    - |
      curl http://nginx
      curl http://localhost:8080 || echo "Won't work"
      curl http://127.0.0.1:8080 || echo "Won't work"
