steps:
- name: 'anshulpatel25/gcp:latest'
  entrypoint: 'bash'
  args:
    - '-cex'
    - |
      docker-compose -f docker-compose.yml up -d
      curl http://nginx || echo "checking"
      curl http://localhost:8080 || echo "Won't work"
      curl http://127.0.0.1:8080 || echo "Won't work"
